apiVersion: batch/v1
kind: Job
metadata:
  name: granite-image-puller
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  parallelism: 2
  completions: 2
  ttlSecondsAfterFinished: 100
  template:
    spec:
      containers:
      - name: image-puller-granite
        imagePullPolicy: IfNotPresent
        image: quay.io/redhat-ai-services/modelcar-catalog:granite-3.2-8b-instruct
        command: ["sh", "-c", "echo 'Granite image pulled successfully to node cache'; sleep 30"]
        resources:
          limits:
            cpu: '2'
            memory: 16Gi
          requests:
            cpu: '2'
            memory: 8Gi
      restartPolicy: Never
      tolerations:
        - key: nvidia.com/gpu
          operator: Equal
          value: 'True'
          effect: NoSchedule
  backoffLimit: 4
---
apiVersion: batch/v1
kind: Job
metadata:
  name: llama-image-puller
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  parallelism: 2
  completions: 2
  ttlSecondsAfterFinished: 100
  template:
    spec:
      containers:
      - name: image-puller-llama
        imagePullPolicy: IfNotPresent
        image: quay.io/redhat-ai-services/modelcar-catalog:llama-3.2-3b-instruct
        command: ["sh", "-c", "echo 'Llama image pulled successfully to node cache'; sleep 30"]
        resources:
          limits:
            cpu: '2'
            memory: 16Gi
          requests:
            cpu: '2'
            memory: 8Gi
      restartPolicy: Never
      tolerations:
        - key: nvidia.com/gpu
          operator: Equal
          value: 'True'
          effect: NoSchedule
  backoffLimit: 4
